// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xvojnnbjnleakecogqnd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2b2pubmJqbmxlYWtlY29ncW5kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MTc1MDYsImV4cCI6MjA2OTE5MzUwNn0.-sYUmLS3v52G9MZ6BdElj9aR-_6yugOmJA1OdgBRsEc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});